Added better comments and added testing runs in both normal and sanitizer build

diff --git a/.github/workflows/ci_build_and_test.yml b/.github/workflows/ci_build_and_test.yml
--- a/.github/workflows/ci_build_and_test.yml
+++ b/.github/workflows/ci_build_and_test.yml
@@ -17,6 +17,12 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      # additional step
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
+
       # Step 2: Cache APT packages to speed up installs.
       # This caches downloaded .deb packages in ./apt-cache inside the workspace.
       # On a cache hit, apt-get can reuse them instead of downloading again.
@@ -89,9 +95,19 @@ jobs:
       - name: Build documentation
         run: cmake --build build --target doc_doxygen
 
-      # Step 11: Run unit tests (enable once tests exist)
-      # - name: Run unit tests
-      #   run: ctest --test-dir build --output-on-failure -j"$(nproc)"
+      # Step 11: Run unit tests and pass errors to review dog. Set fail-on-error=false
+      - name: Run unit tests and annotate
+        run: |
+          ctest --test-dir build --output-on-failure --no-compress-output -T Test || true
+
+      # Convert CTest XML → Reviewdog format
+          reviewdog -f=junit \
+            -name="gtest" \
+            -reporter=github-pr-review \
+            -fail-on-error=false \
+            < build/Testing/*/Test.xml
+        env:
+          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   # ASan build + test (separate job, fresh build tree)
   build_and_test_asan:
@@ -102,6 +118,12 @@ jobs:
       # Step 1: Checkout the repository
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      # additional step
+      - name: Install reviewdog
+        uses: reviewdog/action-setup@v1
+        with:
+          reviewdog_version: latest
 
       # Step 2: Reuse the same APT cache as the normal build job
       - name: Cache APT packages
@@ -151,6 +173,15 @@ jobs:
       - name: Build ASan project
         run: cmake --build build_asan -- -j"$(nproc)"
 
-      # Step 8: Optionally run ASan tests once they exist
-      # - name: Run ASan tests
-      #   run: ctest --test-dir build_asan --output-on-failure -j"$(nproc)"
+      # Step 11: Run unit tests and pass errors to review dog. Set fail-on-error=false. Tests are run in both builds for safety!
+      - name: Run ASan tests and annotate
+        run: |
+          ctest --test-dir build_asan --output-on-failure --no-compress-output -T Test || true
+
+          reviewdog -f=junit \
+            -name="gtest-asan" \
+            -reporter=github-pr-review \
+            -fail-on-error=false \
+            < build_asan/Testing/*/Test.xml
+        env:
+          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
